name: Build

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  workflow_dispatch:

jobs:
  build:
    runs-on: macos-11

    steps:
      - uses: actions/checkout@v3
      
      - uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Build app
        run: |
          yarn
          yarn tauri build
          
      - run: ls
      
      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: Bundle
          path: ./src-tauri/target/release/bundle/
